server:
   #address: 192.168.0.112
   port: 9901
spring:
    cloud:
      consul:
        host: 127.0.0.1
        port: 8500
        discovery:
          #healthCheckPath: /
          #healthCheckInterval: 15s
          instance-id: consul-miya
          tags: dev
    application:
      name: consul-miya
